### ISSUE TITLE
Some leagues not working since last update

### ISSUE THREAD

**Issue by Stoffbeuteluwe** [LukeSkywalker92/MMM-SoccerLiveScore#18]

**Comment by zolabus** [comment]
Same prolem after update it doesn't work anymore

**Comment by ashes2diamonds** [comment]
Module stopped working after last update. Please fix this is a great module. very useful!

**Comment by CyruS1337** [comment]
i have the same problem, the modules dont work after the update

**Comment by LukeSkywalker92** [comment]
i reverted the last update. so it should work again

**Comment by zolabus** [comment]
so what shoul we do to make it work again?

**Comment by zolabus** [comment]
I did a git pull but still not working

**Comment by ashes2diamonds** [comment]
did git pull inside the MMM-SoccerLiveScore directory, then restarted MagicMirror with pm2 and it works again for me. Thanks.
