### ISSUE TITLE
Only Header-Text is visible

### ISSUE THREAD

**Issue by juergli** [LukeSkywalker92/MMM-SoccerLiveScore#2]
I can't see any results or Pictures on the mirror.

What I did:
1. git clone https://github.com/LukeSkywalker92/MMM-SoccerLiveScore.git
2. In the config.js file I copied this code:
   {
	module: 'MMM-SoccerLiveScore',
	position: 'bottom_left',
	header: 'Fussball',
	config: {
		leagues: [35, 1, 9],
        showNames: true,
        showLogos: true,
        displayTime: 60 * 1000,
        showTables: true
	}
},

Any idea, what is wrong?
Thanks!
Greetings, juergli

**Comment by LukeSkywalker92** [comment]
Hey. I need more information to find the problem. Can you please post your console output?
Best 
Luke

**Comment by juergli** [comment]
Hi Luke
I am sorry, but now the module works. I didn't anything. I think, there was an offline time of the sports servers! Thank You!
Juergli
